version: '3'

# back-up in case

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './mariadb'

# services

services:
    mariadb:
        image: debian:buster
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
    wordpress:
        image: debian:buster
        restart: always 
        volumes:
            - wordpress:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
        depends_on:
            - mariadb
    nginx:
        image: debian:buster
        restart: always
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - intra
        tty: true
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress

# link between services

networks:
    intra:
        driver: bridge